// Generated by bin/build-kb.mjs from psychometrics_kb/**/*.md.
// Edit the Markdown KB files, then run npm run kb:build.
export const MARKDOWN_KB_TOPICS = [
  {
    "id": "kb_cfa_model_fit",
    "title": "CFA model fit is evidence to interpret, not a mechanical gate",
    "source": {
      "citation": "Psychometrics KB curation",
      "type": "kb_note",
      "note": "Curated structured knowledge note.",
      "path": "psychometrics_kb/cfa_sem/cfa_model_fit.md"
    },
    "relatedAnalyses": [
      "cfa",
      "ordinal_cfa",
      "reliability_validity"
    ],
    "keywords": [
      "CFA",
      "SEM",
      "model fit",
      "CFI",
      "TLI",
      "RMSEA",
      "SRMR",
      "residuals",
      "modification indices",
      "factor loading",
      "확인적 요인분석",
      "구조방정식",
      "모형적합도",
      "잔차",
      "수정지수",
      "요인부하량"
    ],
    "summary": "CFA fit indices help diagnose whether a hypothesized measurement model is plausible, but they do not validate a scale by themselves. Fit should be interpreted with loadings, residuals, competing models, theory, sample features, and response format.",
    "checks": [
      "Inspect factor loadings, residual correlations, standard errors, and inadmissible estimates.",
      "Report plausible alternative models rather than repairing fit only through modification indices.",
      "Avoid rigid CFI/RMSEA/SRMR cutoffs as automatic pass/fail decisions."
    ],
    "useWhen": [
      "A hypothesized factor structure is supplied.",
      "The user asks whether CFA results are acceptable."
    ]
  },
  {
    "id": "kb_efa_cfa_sem_workflow",
    "title": "EFA, CFA, and SEM answer different stages of the measurement-model workflow",
    "source": {
      "citation": "김수영 (2016). 구조방정식 모형의 기본과 확장: Mplus 예제와 함께. 학지사.",
      "type": "book_toc_guided_summary",
      "note": "Paraphrased SEM knowledge note guided by the book title and table of contents; no source text reproduction.",
      "path": "psychometrics_kb/cfa_sem/efa_cfa_sem_workflow.md"
    },
    "relatedAnalyses": [
      "efa_dimensionality",
      "cfa",
      "ordinal_cfa"
    ],
    "keywords": [
      "EFA",
      "CFA",
      "SEM workflow",
      "factor extraction",
      "factor rotation",
      "specification",
      "identification",
      "estimation",
      "exploratory factor analysis",
      "confirmatory factor analysis",
      "탐색적 요인분석",
      "확인적 요인분석",
      "요인추출",
      "요인회전",
      "모형설정",
      "모형판별"
    ],
    "summary": "EFA is useful when the latent structure is uncertain; CFA tests a specified measurement model; SEM extends the model to structural paths among latent or observed variables. Mixing these stages without a decision trail can overstate evidence.",
    "checks": [
      "Use EFA for discovery and CFA for confirmation when sample size and design allow separation.",
      "In CFA, document specification, identification, estimation, fit evaluation, and model revisions.",
      "Do not treat an EFA-derived structure tested in the same sample as fully confirmed without caveats."
    ],
    "useWhen": [
      "The user asks whether to run EFA, CFA, or SEM.",
      "A scale-development workflow needs sequencing rather than one-off model fit."
    ]
  },
  {
    "id": "kb_measurement_invariance",
    "title": "Measurement invariance should precede group score comparison",
    "source": {
      "citation": "Psychometrics KB curation",
      "type": "kb_note",
      "note": "Curated structured knowledge note.",
      "path": "psychometrics_kb/cfa_sem/measurement_invariance.md"
    },
    "relatedAnalyses": [
      "measurement_invariance",
      "dif_screening",
      "ordinal_cfa",
      "cfa"
    ],
    "keywords": [
      "measurement invariance",
      "configural",
      "metric",
      "scalar",
      "strict",
      "partial invariance",
      "latent mean",
      "group comparison",
      "측정동일성",
      "형태동일성",
      "측정단위동일성",
      "절편동일성",
      "잠재평균",
      "집단비교"
    ],
    "summary": "Group comparisons require evidence that the construct is measured comparably. Configural, metric, scalar, and sometimes strict invariance checks create a decision trail before comparing latent means or observed scores.",
    "checks": [
      "Require an explicit grouping variable and adequate group sizes.",
      "Check configural fit before constraining loadings or thresholds/intercepts.",
      "If full invariance fails, consider partial invariance with transparent item-level justification."
    ],
    "useWhen": [
      "The user wants to compare groups.",
      "The study includes gender, language, site, culture, disability, or demographic subgroup comparisons."
    ]
  },
  {
    "id": "kb_ordinal_cfa",
    "title": "Ordinal CFA is often appropriate for limited Likert categories",
    "source": {
      "citation": "Psychometrics KB curation",
      "type": "kb_note",
      "note": "Curated structured knowledge note.",
      "path": "psychometrics_kb/cfa_sem/ordinal_cfa.md"
    },
    "relatedAnalyses": [
      "ordinal_cfa",
      "cfa",
      "data_screening"
    ],
    "keywords": [
      "ordinal CFA",
      "Likert",
      "WLSMV",
      "DWLS",
      "polychoric",
      "thresholds",
      "categorical indicators",
      "ordered items",
      "순서형 CFA",
      "리커트",
      "다분범주",
      "다분상관",
      "임계값"
    ],
    "summary": "Likert items with limited categories often need ordinal-aware modeling, especially when categories are sparse, skewed, or unevenly used. The estimator choice should follow response diagnostics rather than convenience.",
    "checks": [
      "Inspect category frequencies and missingness before model estimation.",
      "Treat item IDs as ordered indicators when using ordinal CFA templates.",
      "Report estimator choice and thresholds along with fit and loadings."
    ],
    "useWhen": [
      "The response scale has five to seven or fewer ordered categories.",
      "The user asks for CFA on Likert questionnaire data."
    ]
  },
  {
    "id": "kb_sem_data_preparation",
    "title": "SEM data preparation should check sample size, missingness, normality, outliers, and collinearity",
    "source": {
      "citation": "김수영 (2016). 구조방정식 모형의 기본과 확장: Mplus 예제와 함께. 학지사.",
      "type": "book_toc_guided_summary",
      "note": "Paraphrased SEM knowledge note guided by the book title and table of contents; no source text reproduction.",
      "path": "psychometrics_kb/cfa_sem/sem_data_preparation.md"
    },
    "relatedAnalyses": [
      "data_screening",
      "cfa",
      "ordinal_cfa",
      "measurement_invariance"
    ],
    "keywords": [
      "SEM data preparation",
      "structural equation modeling",
      "sample size",
      "normality",
      "outliers",
      "multicollinearity",
      "missing data",
      "covariance matrix",
      "구조방정식",
      "자료 준비",
      "표본크기",
      "정규성",
      "이상값",
      "다중공선성",
      "결측치",
      "공분산행렬"
    ],
    "summary": "SEM recommendations should start with whether the observed data are suitable for the planned model. Sample size, distributional form, missing-data mechanism, outliers, multicollinearity, and whether the analysis uses raw data, covariance matrices, or summary data shape every later estimation and fit decision.",
    "checks": [
      "Ask for sample size, number of observed variables, missing-data pattern, and group sizes before recommending complex SEM.",
      "Screen univariate and multivariate normality, outliers, and near-linear dependence among indicators.",
      "Match the data input format to the planned analysis: raw data, covariance/correlation matrix, or summary statistics."
    ],
    "useWhen": [
      "The user asks whether their data are ready for CFA or SEM.",
      "A SEM model is requested but missingness, normality, or sample size is not specified."
    ]
  },
  {
    "id": "kb_sem_identification_estimation_fit",
    "title": "SEM model evaluation depends on specification, identification, estimation, and fit diagnostics",
    "source": {
      "citation": "김수영 (2016). 구조방정식 모형의 기본과 확장: Mplus 예제와 함께. 학지사.",
      "type": "book_toc_guided_summary",
      "note": "Paraphrased SEM knowledge note guided by the book title and table of contents; no source text reproduction.",
      "path": "psychometrics_kb/cfa_sem/sem_identification_estimation_fit.md"
    },
    "relatedAnalyses": [
      "cfa",
      "ordinal_cfa",
      "reliability_validity"
    ],
    "keywords": [
      "SEM",
      "model specification",
      "identification",
      "estimation",
      "maximum likelihood",
      "least squares",
      "model fit",
      "chi-square",
      "CFI",
      "TLI",
      "RMSEA",
      "SRMR",
      "구조방정식",
      "모형 설정",
      "모형 판별",
      "모형 추정",
      "최대우도",
      "최소제곱",
      "적합도"
    ],
    "summary": "A SEM model should be evaluated as a sequence: specify the theoretical model, confirm identification, choose an estimator that matches the data, inspect global fit, examine local diagnostics, and interpret parameters only within that decision trail.",
    "checks": [
      "Confirm the model is identified before interpreting fit or parameter estimates.",
      "Choose estimation methods according to response scale, distribution, missing data, and sample size.",
      "Read fit indices together with residuals, standard errors, parameter plausibility, and alternative models."
    ],
    "useWhen": [
      "The user asks how to judge SEM or CFA fit.",
      "A generated model has fit indices but no identification or estimation discussion."
    ]
  },
  {
    "id": "kb_sem_item_parcels",
    "title": "Item parceling can simplify SEM but may hide measurement problems",
    "source": {
      "citation": "김수영 (2016). 구조방정식 모형의 기본과 확장: Mplus 예제와 함께. 학지사.",
      "type": "book_toc_guided_summary",
      "note": "Paraphrased SEM knowledge note guided by the book title and table of contents; no source text reproduction.",
      "path": "psychometrics_kb/cfa_sem/sem_item_parcels.md"
    },
    "relatedAnalyses": [
      "cfa",
      "ordinal_cfa",
      "reliability_validity"
    ],
    "keywords": [
      "item parceling",
      "parcels",
      "SEM parcels",
      "CFA parcels",
      "latent variable indicators",
      "unidimensionality",
      "문항묶음",
      "문항꾸러미",
      "구조방정식 문항묶음",
      "단일차원성",
      "잠재변수 지표"
    ],
    "summary": "Item parcels reduce model complexity and can improve estimation stability, but they can also mask multidimensionality, local dependence, DIF, and poorly functioning items. Parceling should be justified before it is used.",
    "checks": [
      "Check item-level dimensionality and content coverage before forming parcels.",
      "Explain the parceling method and why parcels are appropriate for the construct.",
      "Avoid parceling when the goal is item-level diagnosis, DIF, or response-category evaluation."
    ],
    "useWhen": [
      "The user proposes item parcels to improve CFA or SEM fit.",
      "A model has many items relative to sample size and parceling is being considered."
    ]
  },
  {
    "id": "kb_sem_latent_growth_sample_size",
    "title": "Latent growth and SEM sample-size planning require model-specific assumptions",
    "source": {
      "citation": "김수영 (2016). 구조방정식 모형의 기본과 확장: Mplus 예제와 함께. 학지사.",
      "type": "book_toc_guided_summary",
      "note": "Paraphrased SEM knowledge note guided by the book title and table of contents; no source text reproduction.",
      "path": "psychometrics_kb/cfa_sem/sem_latent_growth_sample_size.md"
    },
    "relatedAnalyses": [
      "cfa",
      "reliability_validity",
      "data_screening"
    ],
    "keywords": [
      "latent growth model",
      "latent growth",
      "LGM",
      "longitudinal SEM",
      "SEM sample size",
      "sample size planning",
      "sample size",
      "power",
      "RMSEA",
      "Satorra Saris",
      "Muthen Muthen",
      "MacCallum Browne Sugawara",
      "잠재성장모형",
      "잠재성장",
      "종단 구조방정식",
      "표본크기",
      "표본크기 결정",
      "검정력",
      "모형복잡도"
    ],
    "summary": "SEM sample-size planning depends on model complexity, estimator, missing data, distribution, group count, and desired power. Latent growth models add repeated-measure structure, growth-factor interpretation, and longitudinal missing-data concerns.",
    "checks": [
      "Avoid one-size-fits-all SEM sample-size rules detached from model degrees of freedom and estimator.",
      "For latent growth, specify time scores, growth factors, residual structure, and missing-data handling.",
      "Consider simulation or RMSEA/power-based planning for complex SEM rather than relying only on N-to-parameter ratios."
    ],
    "useWhen": [
      "The user asks whether sample size is enough for SEM or longitudinal growth modeling.",
      "The model includes repeated measures, growth factors, multiple groups, or many parameters."
    ]
  },
  {
    "id": "kb_sem_measurement_invariance_multigroup",
    "title": "Multigroup SEM and MIMIC models can test measurement invariance and group differences",
    "source": {
      "citation": "김수영 (2016). 구조방정식 모형의 기본과 확장: Mplus 예제와 함께. 학지사.",
      "type": "book_toc_guided_summary",
      "note": "Paraphrased SEM knowledge note guided by the book title and table of contents; no source text reproduction.",
      "path": "psychometrics_kb/cfa_sem/sem_measurement_invariance_multigroup.md"
    },
    "relatedAnalyses": [
      "measurement_invariance",
      "dif_screening",
      "cfa",
      "ordinal_cfa"
    ],
    "keywords": [
      "multigroup SEM",
      "measurement invariance",
      "MIMIC model",
      "configural invariance",
      "metric invariance",
      "scalar invariance",
      "structural coefficient equality",
      "group difference",
      "다집단 구조방정식",
      "측정불변성",
      "MIMIC 모형",
      "형태동일성",
      "측정단위동일성",
      "절편동일성",
      "구조계수 동일성",
      "집단차이"
    ],
    "summary": "Group comparisons in SEM should distinguish measurement invariance from structural group differences. Multigroup CFA/SEM checks equality constraints across groups, while MIMIC models can screen direct effects of covariates on indicators or factors.",
    "checks": [
      "Test measurement invariance before comparing latent means or structural paths.",
      "Separate measurement-parameter equality from structural-coefficient equality.",
      "Use MIMIC direct effects as item/functioning signals that need substantive review."
    ],
    "useWhen": [
      "The user wants to compare groups in CFA or SEM.",
      "The model includes group variables, covariates, MIMIC paths, or suspected measurement bias."
    ]
  },
  {
    "id": "kb_sem_mediation_moderation",
    "title": "SEM mediation and moderation require explicit indirect, interaction, and model-comparison logic",
    "source": {
      "citation": "김수영 (2016). 구조방정식 모형의 기본과 확장: Mplus 예제와 함께. 학지사.",
      "type": "book_toc_guided_summary",
      "note": "Paraphrased SEM knowledge note guided by the book title and table of contents; no source text reproduction.",
      "path": "psychometrics_kb/cfa_sem/sem_mediation_moderation.md"
    },
    "relatedAnalyses": [
      "cfa",
      "reliability_validity"
    ],
    "keywords": [
      "SEM mediation",
      "SEM moderation",
      "indirect effect",
      "bootstrap",
      "moderated mediation",
      "MIMIC",
      "latent interaction",
      "nested model",
      "nonnested model",
      "매개효과",
      "조절효과",
      "부트스트래핑",
      "조절된 매개효과",
      "잠재변수 상호작용",
      "내재모형",
      "비내재모형"
    ],
    "summary": "Mediation, moderation, and moderated mediation in SEM are not just extra paths. The analysis needs a defensible causal ordering, indirect-effect testing, interaction specification, and model comparison strategy.",
    "checks": [
      "Use bootstrap confidence intervals or another explicit method for indirect effects.",
      "Distinguish observed-variable interaction, latent interaction, MIMIC, and multigroup approaches.",
      "Compare nested and nonnested models with methods appropriate to the relationship between models."
    ],
    "useWhen": [
      "The user asks whether a variable mediates or moderates an SEM relation.",
      "A model includes indirect effects, latent interactions, or group-conditional effects."
    ]
  },
  {
    "id": "kb_sem_non_normal_ordinal_reliability",
    "title": "SEM with nonnormal, binary, ordinal, or reliability-focused indicators needs estimator-aware interpretation",
    "source": {
      "citation": "김수영 (2016). 구조방정식 모형의 기본과 확장: Mplus 예제와 함께. 학지사.",
      "type": "book_toc_guided_summary",
      "note": "Paraphrased SEM knowledge note guided by the book title and table of contents; no source text reproduction.",
      "path": "psychometrics_kb/cfa_sem/sem_non_normal_ordinal_reliability.md"
    },
    "relatedAnalyses": [
      "ordinal_cfa",
      "cfa",
      "reliability_validity",
      "data_screening"
    ],
    "keywords": [
      "nonnormal indicators",
      "ordinal indicators",
      "binary indicators",
      "categorical CFA",
      "robust estimator",
      "WLSMV",
      "higher-order factor",
      "SEM reliability",
      "discriminant validity",
      "비정규 지표변수",
      "이분형 자료",
      "순위형 자료",
      "범주형 CFA",
      "강건추정",
      "고차 요인분석",
      "측정모형 신뢰도",
      "차별타당성"
    ],
    "summary": "When indicators are nonnormal, binary, ordinal, or used to support reliability/validity claims, SEM output must be interpreted through estimator choice, threshold/category diagnostics, higher-order structure, and discriminant-validity evidence.",
    "checks": [
      "Match estimator and link functions to binary or ordinal indicators rather than defaulting to continuous ML.",
      "Examine whether higher-order factor models are theoretically justified and empirically identified.",
      "Report SEM-based reliability and discriminant-validity evidence with assumptions, not as automatic pass/fail rules."
    ],
    "useWhen": [
      "The user has Likert, binary, or nonnormal indicators in SEM.",
      "The user asks for reliability, higher-order factors, or discriminant validity from CFA/SEM."
    ]
  },
  {
    "id": "kb_logistic_regression_dif",
    "title": "Logistic regression DIF can screen uniform and nonuniform effects",
    "source": {
      "citation": "Psychometrics KB curation",
      "type": "kb_note",
      "note": "Curated structured knowledge note.",
      "path": "psychometrics_kb/dif/logistic_regression_dif.md"
    },
    "relatedAnalyses": [
      "dif_screening"
    ],
    "keywords": [
      "DIF",
      "logistic regression DIF",
      "uniform DIF",
      "nonuniform DIF",
      "group by trait interaction",
      "ordinal logistic",
      "차별기능문항",
      "로지스틱 회귀",
      "균일 DIF",
      "비균일 DIF",
      "상호작용"
    ],
    "summary": "Logistic regression DIF models item response as a function of trait proxy, group, and their interaction. It can screen for uniform group differences and nonuniform group-by-trait effects.",
    "checks": [
      "Include the matching trait proxy before testing group effects.",
      "Inspect both statistical significance and effect size.",
      "For ordered categories, use an ordinal approach or justify the scoring transformation."
    ],
    "useWhen": [
      "The user asks about uniform or nonuniform DIF.",
      "A flexible item-level fairness screen is needed before expert review."
    ]
  },
  {
    "id": "kb_mantel_haenszel_dif",
    "title": "Mantel-Haenszel DIF is a screening method for grouped item functioning",
    "source": {
      "citation": "Psychometrics KB curation",
      "type": "kb_note",
      "note": "Curated structured knowledge note.",
      "path": "psychometrics_kb/dif/mantel_haenszel.md"
    },
    "relatedAnalyses": [
      "dif_screening"
    ],
    "keywords": [
      "DIF",
      "Mantel-Haenszel",
      "MH DIF",
      "focal group",
      "reference group",
      "matching score",
      "common odds ratio",
      "차별기능문항",
      "만텔-헨젤",
      "초점집단",
      "참조집단",
      "매칭점수"
    ],
    "summary": "Mantel-Haenszel DIF compares item performance across groups after matching on a total score or trait proxy. It is often used as an interpretable screening method, especially for binary or suitably categorized items.",
    "checks": [
      "Define focal and reference groups before running the screen.",
      "Use a defensible matching variable and inspect sample size within score strata.",
      "Treat DIF flags as prompts for expert review, not automatic evidence of bias."
    ],
    "useWhen": [
      "The user requests item-level fairness screening.",
      "The item format and grouping design fit Mantel-Haenszel assumptions."
    ]
  },
  {
    "id": "kb_binary_irt_models",
    "title": "1PL, 2PL, and 3PL models target binary item responses",
    "source": {
      "citation": "Psychometrics KB curation",
      "type": "kb_note",
      "note": "Curated structured knowledge note.",
      "path": "psychometrics_kb/irt/1pl_2pl_3pl.md"
    },
    "relatedAnalyses": [
      "irt_binary"
    ],
    "keywords": [
      "IRT",
      "Rasch",
      "1PL",
      "2PL",
      "3PL",
      "binary items",
      "difficulty",
      "discrimination",
      "guessing",
      "item response theory",
      "문항반응이론",
      "라쉬",
      "이분문항",
      "난이도",
      "변별도",
      "추측도"
    ],
    "summary": "Binary IRT models differ in whether they estimate item difficulty only, item discrimination, or lower asymptote/guessing. They should not be applied directly to five-point Likert responses without recoding rationale and loss-of-information review.",
    "checks": [
      "Confirm the response format is binary before recommending 1PL, 2PL, or 3PL.",
      "Check dimensionality and local independence before interpreting item parameters.",
      "Treat model choice as a substantive and empirical decision, not just a software default."
    ],
    "useWhen": [
      "The user has dichotomous scored items.",
      "The user asks whether Rasch, 2PL, or 3PL is appropriate."
    ]
  },
  {
    "id": "kb_polytomous_irt_models",
    "title": "GRM and GPCM are common choices for ordered polytomous items",
    "source": {
      "citation": "Psychometrics KB curation",
      "type": "kb_note",
      "note": "Curated structured knowledge note.",
      "path": "psychometrics_kb/irt/grm_gpcm.md"
    },
    "relatedAnalyses": [
      "irt_polytomous"
    ],
    "keywords": [
      "graded response model",
      "GRM",
      "generalized partial credit model",
      "GPCM",
      "polytomous IRT",
      "thresholds",
      "category response",
      "mirt",
      "등급반응모형",
      "일반화부분점수모형",
      "다분문항",
      "임계값"
    ],
    "summary": "Ordered Likert items can be examined with polytomous IRT models such as the graded response model or generalized partial credit model when dimensionality and local independence are defensible.",
    "checks": [
      "Check category ordering and sparse categories before calibration.",
      "Review item discrimination, threshold ordering, item fit, and information curves.",
      "Use IRT as a sensitivity analysis unless sample size and model assumptions are strong."
    ],
    "useWhen": [
      "The study uses ordered Likert or rating-scale items.",
      "The user asks for item-level diagnostics beyond CTT reliability."
    ]
  },
  {
    "id": "kb_irt_item_fit",
    "title": "IRT item fit should be read with dimensionality and local dependence",
    "source": {
      "citation": "Psychometrics KB curation",
      "type": "kb_note",
      "note": "Curated structured knowledge note.",
      "path": "psychometrics_kb/irt/item_fit.md"
    },
    "relatedAnalyses": [
      "irt_polytomous",
      "irt_binary",
      "data_screening"
    ],
    "keywords": [
      "item fit",
      "IRT fit",
      "local dependence",
      "residuals",
      "Q3",
      "S-X2",
      "item information",
      "differential item functioning",
      "문항적합도",
      "국소독립성",
      "잔차",
      "문항정보",
      "문항진단"
    ],
    "summary": "IRT item fit statistics are diagnostic signals. Poor fit may reflect multidimensionality, local dependence, category problems, sample mismatch, or item wording rather than a simple delete/keep decision.",
    "checks": [
      "Review dimensionality and local-dependence diagnostics before interpreting item fit.",
      "Combine statistical flags with expert item review.",
      "Document whether flagged items are revised, removed, retained, or sent to sensitivity analysis."
    ],
    "useWhen": [
      "IRT is recommended or requested.",
      "The user asks how to act on item fit warnings."
    ]
  },
  {
    "id": "kb_lavaan_templates",
    "title": "lavaan templates should stay tied to explicit model assumptions",
    "source": {
      "citation": "Psychometrics KB curation",
      "type": "code_guidance",
      "note": "Curated structured knowledge note.",
      "path": "psychometrics_kb/r_code/lavaan_templates.md"
    },
    "relatedAnalyses": [
      "ordinal_cfa",
      "cfa",
      "measurement_invariance"
    ],
    "keywords": [
      "lavaan",
      "CFA code",
      "SEM code",
      "WLSMV",
      "ordered items",
      "measurementInvariance",
      "R template",
      "분석 코드",
      "R 코드",
      "확인적 요인분석 코드",
      "측정동일성 코드"
    ],
    "summary": "lavaan code templates are useful only when the item-to-factor map, ordered item handling, missing-data rule, grouping variable, and model-comparison plan are explicit. Generated code should be a starting point, not hidden analysis authority.",
    "checks": [
      "Replace placeholder item IDs and data frame names before execution.",
      "Match estimator and ordered-item arguments to the response format.",
      "Report any model modifications separately from the initial hypothesized model."
    ],
    "useWhen": [
      "The consultation generates CFA or measurement-invariance R code.",
      "The user asks for reproducible lavaan analysis templates."
    ]
  },
  {
    "id": "kb_mirt_templates",
    "title": "mirt templates should require response format and dimensionality checks",
    "source": {
      "citation": "Psychometrics KB curation",
      "type": "code_guidance",
      "note": "Curated structured knowledge note.",
      "path": "psychometrics_kb/r_code/mirt_templates.md"
    },
    "relatedAnalyses": [
      "irt_polytomous",
      "irt_binary"
    ],
    "keywords": [
      "mirt",
      "IRT code",
      "graded response model",
      "GPCM",
      "Rasch",
      "itemfit",
      "M2",
      "item information",
      "R template",
      "분석 코드",
      "문항반응이론 코드",
      "등급반응모형 코드"
    ],
    "summary": "mirt templates should be selected by item response format and dimensionality evidence. A graded response template is suitable for ordered categories, while binary models need dichotomous items and different interpretation.",
    "checks": [
      "Confirm whether items are binary or ordered polytomous before choosing item type.",
      "Check dimensionality and local dependence before interpreting parameters.",
      "Report item fit, thresholds or difficulties, discrimination, and information with caveats."
    ],
    "useWhen": [
      "The consultation generates IRT R code.",
      "The user asks for mirt-based item diagnostics."
    ]
  },
  {
    "id": "kb_mplus_sem_templates",
    "title": "Mplus SEM templates require explicit variable lists, estimator choices, and missing-data rules",
    "source": {
      "citation": "김수영 (2016). 구조방정식 모형의 기본과 확장: Mplus 예제와 함께. 학지사.",
      "type": "book_toc_guided_summary",
      "note": "Paraphrased SEM/Mplus knowledge note guided by the book title and table of contents; no source text reproduction.",
      "path": "psychometrics_kb/r_code/mplus_sem_templates.md"
    },
    "relatedAnalyses": [
      "cfa",
      "ordinal_cfa",
      "measurement_invariance",
      "irt_polytomous"
    ],
    "keywords": [
      "Mplus",
      "Mplus input",
      "Mplus syntax",
      "SEM code",
      "CFA code",
      "estimator",
      "categorical",
      "missing",
      "grouping",
      "구조방정식 Mplus",
      "Mplus 입력파일",
      "Mplus 문법",
      "분석 코드",
      "범주형 지표",
      "결측 처리"
    ],
    "summary": "Mplus examples are helpful for SEM, CFA, mediation, invariance, categorical indicators, and growth models, but generated syntax must make the data file, variable names, categorical declarations, missing codes, estimator, grouping, and model block explicit.",
    "checks": [
      "Replace placeholder variable names and confirm the data file matches the Mplus `NAMES`, `USEVARIABLES`, and missing-value declarations.",
      "Use `CATEGORICAL`, grouping, and estimator options only when they match the item format and design.",
      "Keep generated syntax as a reviewed template; do not treat it as proof that the model is appropriate."
    ],
    "useWhen": [
      "The user asks for Mplus examples or syntax.",
      "The analysis plan includes CFA, SEM, invariance, mediation, categorical indicators, or latent growth models in Mplus."
    ]
  },
  {
    "id": "kb_reliability_reporting",
    "title": "Reliability reporting should include precision and context",
    "source": {
      "citation": "AERA, APA, & NCME (2014). Standards for Educational and Psychological Testing.",
      "type": "book_paraphrase",
      "note": "Paraphrased topic note; not a reproduction of the source text.",
      "path": "psychometrics_kb/standards/reliability_reporting.md"
    },
    "relatedAnalyses": [
      "reliability_validity"
    ],
    "keywords": [
      "reliability",
      "precision",
      "cronbach alpha",
      "omega",
      "standard error of measurement",
      "SEM",
      "decision consistency",
      "신뢰도",
      "정밀도",
      "크론바흐 알파",
      "오메가",
      "측정오차",
      "표준오차",
      "의사결정 일관성"
    ],
    "summary": "Reliability evidence should describe the precision of scores under defined conditions. A single alpha coefficient is not enough when scores are interpreted at different ranges, used for decisions, or compared across groups.",
    "checks": [
      "Report the sample, form, administration mode, and score level tied to the estimate.",
      "Add standard errors, conditional precision, or decision consistency when individual decisions are made.",
      "Avoid using alpha as an absolute cutoff detached from construct breadth and intended use."
    ],
    "useWhen": [
      "The user asks how to report reliability.",
      "The score will be interpreted for individuals, groups, bands, or classifications."
    ]
  },
  {
    "id": "kb_testing_standards",
    "title": "Testing standards organize evidence, operations, rights, and use",
    "source": {
      "citation": "AERA, APA, & NCME (2014). Standards for Educational and Psychological Testing.",
      "type": "book_paraphrase",
      "note": "Paraphrased topic note; not a reproduction of the source text.",
      "path": "psychometrics_kb/standards/testing_standards.md"
    },
    "relatedAnalyses": [
      "reliability_validity",
      "data_screening"
    ],
    "keywords": [
      "testing standards",
      "standards",
      "AERA",
      "APA",
      "NCME",
      "validity",
      "reliability",
      "fairness",
      "documentation",
      "검사 기준",
      "심리검사 기준",
      "타당도",
      "신뢰도",
      "공정성",
      "문서화"
    ],
    "summary": "Testing standards are best used as an organizing framework for evidence, not as a checklist of automatic pass/fail rules. A defensible test use connects validity, reliability/precision, fairness, operations, documentation, rights, and intended decisions.",
    "checks": [
      "Ask what score interpretation and use the evidence is meant to support.",
      "Separate technical evidence from administrative, reporting, privacy, and rights issues.",
      "Treat new populations, languages, settings, or decisions as requiring renewed evidence."
    ],
    "useWhen": [
      "The user asks whether an instrument is generally acceptable or standard-compliant.",
      "A report needs a high-level evidence map before specific analyses are chosen."
    ]
  },
  {
    "id": "kb_validity_evidence",
    "title": "Validity evidence should be organized around the proposed score use",
    "source": {
      "citation": "AERA, APA, & NCME (2014). Standards for Educational and Psychological Testing.",
      "type": "book_paraphrase",
      "note": "Paraphrased topic note; not a reproduction of the source text.",
      "path": "psychometrics_kb/standards/validity_evidence.md"
    },
    "relatedAnalyses": [
      "reliability_validity",
      "ordinal_cfa",
      "cfa",
      "efa_dimensionality"
    ],
    "keywords": [
      "validity",
      "validation",
      "validity argument",
      "content evidence",
      "response process",
      "internal structure",
      "relations to other variables",
      "consequences",
      "타당도",
      "타당화",
      "내용타당도",
      "반응과정",
      "내적구조",
      "준거",
      "결과"
    ],
    "summary": "Validity is an argument about whether evidence supports a particular interpretation and use of scores. Internal structure is only one part of that argument; content relevance, response processes, relations to other variables, consequences, and sample/settings also matter.",
    "checks": [
      "State the intended score use before recommending statistical models.",
      "Link CFA, IRT, reliability, and DIF results back to the construct definition.",
      "Warn when a user treats one coefficient or one fit index as proof of validity."
    ],
    "useWhen": [
      "The user asks whether a scale is valid.",
      "The intended use is vague, new, or broader than the evidence supplied."
    ]
  },
  {
    "id": "kb_itc_adaptation_guidelines",
    "title": "Test adaptation requires construct, language, and cultural evidence",
    "source": {
      "citation": "International Test Commission guidance, summarized as a local KB note.",
      "type": "guideline_summary",
      "note": "Brief paraphrased implementation note.",
      "path": "psychometrics_kb/test_adaptation/itc_guidelines_summary.md"
    },
    "relatedAnalyses": [
      "adaptation_checklist",
      "measurement_invariance",
      "dif_screening"
    ],
    "keywords": [
      "test adaptation",
      "ITC guidelines",
      "translation",
      "back translation",
      "cultural adaptation",
      "equivalence",
      "pilot testing",
      "검사 번안",
      "번역",
      "역번역",
      "문화적 적합성",
      "동등성",
      "파일럿"
    ],
    "summary": "Adapting a test is not just translating item text. The workflow should preserve construct meaning, language clarity, administration comparability, response process, and score interpretation in the target population.",
    "checks": [
      "Document translation, expert review, pilot testing, and item revision decisions.",
      "Check whether the construct and item content carry the same meaning in the target context.",
      "Use invariance and DIF analyses as evidence, not as substitutes for cultural review."
    ],
    "useWhen": [
      "The user mentions translation, localization, or use in a new culture/language.",
      "A scale is imported from another population or setting."
    ]
  }
];
