// Generated by bin/build-kb.mjs from psychometrics_kb/**/*.md.
// Edit the Markdown KB files, then run npm run kb:build.
export const MARKDOWN_KB_TOPICS = [
  {
    "id": "kb_cfa_model_fit",
    "title": "CFA model fit is evidence to interpret, not a mechanical gate",
    "source": {
      "citation": "Psychometrics KB curation",
      "type": "kb_note",
      "note": "Curated structured knowledge note.",
      "path": "psychometrics_kb/cfa_sem/cfa_model_fit.md"
    },
    "relatedAnalyses": [
      "cfa",
      "ordinal_cfa",
      "reliability_validity"
    ],
    "keywords": [
      "CFA",
      "SEM",
      "model fit",
      "CFI",
      "TLI",
      "RMSEA",
      "SRMR",
      "residuals",
      "modification indices",
      "factor loading",
      "확인적 요인분석",
      "구조방정식",
      "모형적합도",
      "잔차",
      "수정지수",
      "요인부하량"
    ],
    "summary": "CFA fit indices help diagnose whether a hypothesized measurement model is plausible, but they do not validate a scale by themselves. Fit should be interpreted with loadings, residuals, competing models, theory, sample features, and response format.",
    "checks": [
      "Inspect factor loadings, residual correlations, standard errors, and inadmissible estimates.",
      "Report plausible alternative models rather than repairing fit only through modification indices.",
      "Avoid rigid CFI/RMSEA/SRMR cutoffs as automatic pass/fail decisions."
    ],
    "useWhen": [
      "A hypothesized factor structure is supplied.",
      "The user asks whether CFA results are acceptable."
    ]
  },
  {
    "id": "kb_measurement_invariance",
    "title": "Measurement invariance should precede group score comparison",
    "source": {
      "citation": "Psychometrics KB curation",
      "type": "kb_note",
      "note": "Curated structured knowledge note.",
      "path": "psychometrics_kb/cfa_sem/measurement_invariance.md"
    },
    "relatedAnalyses": [
      "measurement_invariance",
      "dif_screening",
      "ordinal_cfa",
      "cfa"
    ],
    "keywords": [
      "measurement invariance",
      "configural",
      "metric",
      "scalar",
      "strict",
      "partial invariance",
      "latent mean",
      "group comparison",
      "측정동일성",
      "형태동일성",
      "측정단위동일성",
      "절편동일성",
      "잠재평균",
      "집단비교"
    ],
    "summary": "Group comparisons require evidence that the construct is measured comparably. Configural, metric, scalar, and sometimes strict invariance checks create a decision trail before comparing latent means or observed scores.",
    "checks": [
      "Require an explicit grouping variable and adequate group sizes.",
      "Check configural fit before constraining loadings or thresholds/intercepts.",
      "If full invariance fails, consider partial invariance with transparent item-level justification."
    ],
    "useWhen": [
      "The user wants to compare groups.",
      "The study includes gender, language, site, culture, disability, or demographic subgroup comparisons."
    ]
  },
  {
    "id": "kb_ordinal_cfa",
    "title": "Ordinal CFA is often appropriate for limited Likert categories",
    "source": {
      "citation": "Psychometrics KB curation",
      "type": "kb_note",
      "note": "Curated structured knowledge note.",
      "path": "psychometrics_kb/cfa_sem/ordinal_cfa.md"
    },
    "relatedAnalyses": [
      "ordinal_cfa",
      "cfa",
      "data_screening"
    ],
    "keywords": [
      "ordinal CFA",
      "Likert",
      "WLSMV",
      "DWLS",
      "polychoric",
      "thresholds",
      "categorical indicators",
      "ordered items",
      "순서형 CFA",
      "리커트",
      "다분범주",
      "다분상관",
      "임계값"
    ],
    "summary": "Likert items with limited categories often need ordinal-aware modeling, especially when categories are sparse, skewed, or unevenly used. The estimator choice should follow response diagnostics rather than convenience.",
    "checks": [
      "Inspect category frequencies and missingness before model estimation.",
      "Treat item IDs as ordered indicators when using ordinal CFA templates.",
      "Report estimator choice and thresholds along with fit and loadings."
    ],
    "useWhen": [
      "The response scale has five to seven or fewer ordered categories.",
      "The user asks for CFA on Likert questionnaire data."
    ]
  },
  {
    "id": "kb_logistic_regression_dif",
    "title": "Logistic regression DIF can screen uniform and nonuniform effects",
    "source": {
      "citation": "Psychometrics KB curation",
      "type": "kb_note",
      "note": "Curated structured knowledge note.",
      "path": "psychometrics_kb/dif/logistic_regression_dif.md"
    },
    "relatedAnalyses": [
      "dif_screening"
    ],
    "keywords": [
      "DIF",
      "logistic regression DIF",
      "uniform DIF",
      "nonuniform DIF",
      "group by trait interaction",
      "ordinal logistic",
      "차별기능문항",
      "로지스틱 회귀",
      "균일 DIF",
      "비균일 DIF",
      "상호작용"
    ],
    "summary": "Logistic regression DIF models item response as a function of trait proxy, group, and their interaction. It can screen for uniform group differences and nonuniform group-by-trait effects.",
    "checks": [
      "Include the matching trait proxy before testing group effects.",
      "Inspect both statistical significance and effect size.",
      "For ordered categories, use an ordinal approach or justify the scoring transformation."
    ],
    "useWhen": [
      "The user asks about uniform or nonuniform DIF.",
      "A flexible item-level fairness screen is needed before expert review."
    ]
  },
  {
    "id": "kb_mantel_haenszel_dif",
    "title": "Mantel-Haenszel DIF is a screening method for grouped item functioning",
    "source": {
      "citation": "Psychometrics KB curation",
      "type": "kb_note",
      "note": "Curated structured knowledge note.",
      "path": "psychometrics_kb/dif/mantel_haenszel.md"
    },
    "relatedAnalyses": [
      "dif_screening"
    ],
    "keywords": [
      "DIF",
      "Mantel-Haenszel",
      "MH DIF",
      "focal group",
      "reference group",
      "matching score",
      "common odds ratio",
      "차별기능문항",
      "만텔-헨젤",
      "초점집단",
      "참조집단",
      "매칭점수"
    ],
    "summary": "Mantel-Haenszel DIF compares item performance across groups after matching on a total score or trait proxy. It is often used as an interpretable screening method, especially for binary or suitably categorized items.",
    "checks": [
      "Define focal and reference groups before running the screen.",
      "Use a defensible matching variable and inspect sample size within score strata.",
      "Treat DIF flags as prompts for expert review, not automatic evidence of bias."
    ],
    "useWhen": [
      "The user requests item-level fairness screening.",
      "The item format and grouping design fit Mantel-Haenszel assumptions."
    ]
  },
  {
    "id": "kb_binary_irt_models",
    "title": "1PL, 2PL, and 3PL models target binary item responses",
    "source": {
      "citation": "Psychometrics KB curation",
      "type": "kb_note",
      "note": "Curated structured knowledge note.",
      "path": "psychometrics_kb/irt/1pl_2pl_3pl.md"
    },
    "relatedAnalyses": [
      "irt_binary"
    ],
    "keywords": [
      "IRT",
      "Rasch",
      "1PL",
      "2PL",
      "3PL",
      "binary items",
      "difficulty",
      "discrimination",
      "guessing",
      "item response theory",
      "문항반응이론",
      "라쉬",
      "이분문항",
      "난이도",
      "변별도",
      "추측도"
    ],
    "summary": "Binary IRT models differ in whether they estimate item difficulty only, item discrimination, or lower asymptote/guessing. They should not be applied directly to five-point Likert responses without recoding rationale and loss-of-information review.",
    "checks": [
      "Confirm the response format is binary before recommending 1PL, 2PL, or 3PL.",
      "Check dimensionality and local independence before interpreting item parameters.",
      "Treat model choice as a substantive and empirical decision, not just a software default."
    ],
    "useWhen": [
      "The user has dichotomous scored items.",
      "The user asks whether Rasch, 2PL, or 3PL is appropriate."
    ]
  },
  {
    "id": "kb_polytomous_irt_models",
    "title": "GRM and GPCM are common choices for ordered polytomous items",
    "source": {
      "citation": "Psychometrics KB curation",
      "type": "kb_note",
      "note": "Curated structured knowledge note.",
      "path": "psychometrics_kb/irt/grm_gpcm.md"
    },
    "relatedAnalyses": [
      "irt_polytomous"
    ],
    "keywords": [
      "graded response model",
      "GRM",
      "generalized partial credit model",
      "GPCM",
      "polytomous IRT",
      "thresholds",
      "category response",
      "mirt",
      "등급반응모형",
      "일반화부분점수모형",
      "다분문항",
      "임계값"
    ],
    "summary": "Ordered Likert items can be examined with polytomous IRT models such as the graded response model or generalized partial credit model when dimensionality and local independence are defensible.",
    "checks": [
      "Check category ordering and sparse categories before calibration.",
      "Review item discrimination, threshold ordering, item fit, and information curves.",
      "Use IRT as a sensitivity analysis unless sample size and model assumptions are strong."
    ],
    "useWhen": [
      "The study uses ordered Likert or rating-scale items.",
      "The user asks for item-level diagnostics beyond CTT reliability."
    ]
  },
  {
    "id": "kb_irt_item_fit",
    "title": "IRT item fit should be read with dimensionality and local dependence",
    "source": {
      "citation": "Psychometrics KB curation",
      "type": "kb_note",
      "note": "Curated structured knowledge note.",
      "path": "psychometrics_kb/irt/item_fit.md"
    },
    "relatedAnalyses": [
      "irt_polytomous",
      "irt_binary",
      "data_screening"
    ],
    "keywords": [
      "item fit",
      "IRT fit",
      "local dependence",
      "residuals",
      "Q3",
      "S-X2",
      "item information",
      "differential item functioning",
      "문항적합도",
      "국소독립성",
      "잔차",
      "문항정보",
      "문항진단"
    ],
    "summary": "IRT item fit statistics are diagnostic signals. Poor fit may reflect multidimensionality, local dependence, category problems, sample mismatch, or item wording rather than a simple delete/keep decision.",
    "checks": [
      "Review dimensionality and local-dependence diagnostics before interpreting item fit.",
      "Combine statistical flags with expert item review.",
      "Document whether flagged items are revised, removed, retained, or sent to sensitivity analysis."
    ],
    "useWhen": [
      "IRT is recommended or requested.",
      "The user asks how to act on item fit warnings."
    ]
  },
  {
    "id": "kb_lavaan_templates",
    "title": "lavaan templates should stay tied to explicit model assumptions",
    "source": {
      "citation": "Psychometrics KB curation",
      "type": "code_guidance",
      "note": "Curated structured knowledge note.",
      "path": "psychometrics_kb/r_code/lavaan_templates.md"
    },
    "relatedAnalyses": [
      "ordinal_cfa",
      "cfa",
      "measurement_invariance"
    ],
    "keywords": [
      "lavaan",
      "CFA code",
      "SEM code",
      "WLSMV",
      "ordered items",
      "measurementInvariance",
      "R template",
      "분석 코드",
      "R 코드",
      "확인적 요인분석 코드",
      "측정동일성 코드"
    ],
    "summary": "lavaan code templates are useful only when the item-to-factor map, ordered item handling, missing-data rule, grouping variable, and model-comparison plan are explicit. Generated code should be a starting point, not hidden analysis authority.",
    "checks": [
      "Replace placeholder item IDs and data frame names before execution.",
      "Match estimator and ordered-item arguments to the response format.",
      "Report any model modifications separately from the initial hypothesized model."
    ],
    "useWhen": [
      "The consultation generates CFA or measurement-invariance R code.",
      "The user asks for reproducible lavaan analysis templates."
    ]
  },
  {
    "id": "kb_mirt_templates",
    "title": "mirt templates should require response format and dimensionality checks",
    "source": {
      "citation": "Psychometrics KB curation",
      "type": "code_guidance",
      "note": "Curated structured knowledge note.",
      "path": "psychometrics_kb/r_code/mirt_templates.md"
    },
    "relatedAnalyses": [
      "irt_polytomous",
      "irt_binary"
    ],
    "keywords": [
      "mirt",
      "IRT code",
      "graded response model",
      "GPCM",
      "Rasch",
      "itemfit",
      "M2",
      "item information",
      "R template",
      "분석 코드",
      "문항반응이론 코드",
      "등급반응모형 코드"
    ],
    "summary": "mirt templates should be selected by item response format and dimensionality evidence. A graded response template is suitable for ordered categories, while binary models need dichotomous items and different interpretation.",
    "checks": [
      "Confirm whether items are binary or ordered polytomous before choosing item type.",
      "Check dimensionality and local dependence before interpreting parameters.",
      "Report item fit, thresholds or difficulties, discrimination, and information with caveats."
    ],
    "useWhen": [
      "The consultation generates IRT R code.",
      "The user asks for mirt-based item diagnostics."
    ]
  },
  {
    "id": "kb_reliability_reporting",
    "title": "Reliability reporting should include precision and context",
    "source": {
      "citation": "AERA, APA, & NCME (2014). Standards for Educational and Psychological Testing.",
      "type": "book_paraphrase",
      "note": "Paraphrased topic note; not a reproduction of the source text.",
      "path": "psychometrics_kb/standards/reliability_reporting.md"
    },
    "relatedAnalyses": [
      "reliability_validity"
    ],
    "keywords": [
      "reliability",
      "precision",
      "cronbach alpha",
      "omega",
      "standard error of measurement",
      "SEM",
      "decision consistency",
      "신뢰도",
      "정밀도",
      "크론바흐 알파",
      "오메가",
      "측정오차",
      "표준오차",
      "의사결정 일관성"
    ],
    "summary": "Reliability evidence should describe the precision of scores under defined conditions. A single alpha coefficient is not enough when scores are interpreted at different ranges, used for decisions, or compared across groups.",
    "checks": [
      "Report the sample, form, administration mode, and score level tied to the estimate.",
      "Add standard errors, conditional precision, or decision consistency when individual decisions are made.",
      "Avoid using alpha as an absolute cutoff detached from construct breadth and intended use."
    ],
    "useWhen": [
      "The user asks how to report reliability.",
      "The score will be interpreted for individuals, groups, bands, or classifications."
    ]
  },
  {
    "id": "kb_testing_standards",
    "title": "Testing standards organize evidence, operations, rights, and use",
    "source": {
      "citation": "AERA, APA, & NCME (2014). Standards for Educational and Psychological Testing.",
      "type": "book_paraphrase",
      "note": "Paraphrased topic note; not a reproduction of the source text.",
      "path": "psychometrics_kb/standards/testing_standards.md"
    },
    "relatedAnalyses": [
      "reliability_validity",
      "data_screening"
    ],
    "keywords": [
      "testing standards",
      "standards",
      "AERA",
      "APA",
      "NCME",
      "validity",
      "reliability",
      "fairness",
      "documentation",
      "검사 기준",
      "심리검사 기준",
      "타당도",
      "신뢰도",
      "공정성",
      "문서화"
    ],
    "summary": "Testing standards are best used as an organizing framework for evidence, not as a checklist of automatic pass/fail rules. A defensible test use connects validity, reliability/precision, fairness, operations, documentation, rights, and intended decisions.",
    "checks": [
      "Ask what score interpretation and use the evidence is meant to support.",
      "Separate technical evidence from administrative, reporting, privacy, and rights issues.",
      "Treat new populations, languages, settings, or decisions as requiring renewed evidence."
    ],
    "useWhen": [
      "The user asks whether an instrument is generally acceptable or standard-compliant.",
      "A report needs a high-level evidence map before specific analyses are chosen."
    ]
  },
  {
    "id": "kb_validity_evidence",
    "title": "Validity evidence should be organized around the proposed score use",
    "source": {
      "citation": "AERA, APA, & NCME (2014). Standards for Educational and Psychological Testing.",
      "type": "book_paraphrase",
      "note": "Paraphrased topic note; not a reproduction of the source text.",
      "path": "psychometrics_kb/standards/validity_evidence.md"
    },
    "relatedAnalyses": [
      "reliability_validity",
      "ordinal_cfa",
      "cfa",
      "efa_dimensionality"
    ],
    "keywords": [
      "validity",
      "validation",
      "validity argument",
      "content evidence",
      "response process",
      "internal structure",
      "relations to other variables",
      "consequences",
      "타당도",
      "타당화",
      "내용타당도",
      "반응과정",
      "내적구조",
      "준거",
      "결과"
    ],
    "summary": "Validity is an argument about whether evidence supports a particular interpretation and use of scores. Internal structure is only one part of that argument; content relevance, response processes, relations to other variables, consequences, and sample/settings also matter.",
    "checks": [
      "State the intended score use before recommending statistical models.",
      "Link CFA, IRT, reliability, and DIF results back to the construct definition.",
      "Warn when a user treats one coefficient or one fit index as proof of validity."
    ],
    "useWhen": [
      "The user asks whether a scale is valid.",
      "The intended use is vague, new, or broader than the evidence supplied."
    ]
  },
  {
    "id": "kb_itc_adaptation_guidelines",
    "title": "Test adaptation requires construct, language, and cultural evidence",
    "source": {
      "citation": "International Test Commission guidance, summarized as a local KB note.",
      "type": "guideline_summary",
      "note": "Brief paraphrased implementation note.",
      "path": "psychometrics_kb/test_adaptation/itc_guidelines_summary.md"
    },
    "relatedAnalyses": [
      "adaptation_checklist",
      "measurement_invariance",
      "dif_screening"
    ],
    "keywords": [
      "test adaptation",
      "ITC guidelines",
      "translation",
      "back translation",
      "cultural adaptation",
      "equivalence",
      "pilot testing",
      "검사 번안",
      "번역",
      "역번역",
      "문화적 적합성",
      "동등성",
      "파일럿"
    ],
    "summary": "Adapting a test is not just translating item text. The workflow should preserve construct meaning, language clarity, administration comparability, response process, and score interpretation in the target population.",
    "checks": [
      "Document translation, expert review, pilot testing, and item revision decisions.",
      "Check whether the construct and item content carry the same meaning in the target context.",
      "Use invariance and DIF analyses as evidence, not as substitutes for cultural review."
    ],
    "useWhen": [
      "The user mentions translation, localization, or use in a new culture/language.",
      "A scale is imported from another population or setting."
    ]
  }
];
